language: node_js
node_js:
    - "node"

cache:
    yarn: true

before_script:
    - yarn install
    - yarn run build

script:
    - yarn run test
    - npx codecov

after_success:
    - yarn pack

deploy:
    - provider: releases
      api_key: $GITHUB_TOKEN
      file_glob: true
      file: "typescript-plugin-css-module-types-*.tgz"
      skip_cleanup: true
      on:
          tags: true
    - provider: npm
      skip_cleanup: true
      email: "godlesz@hotmail.de"
      api_key: $NPM_TOKEN
      on:
          tags: true
